=== bintidev/LenguajeMarcas/Binta - Validación-Por-Esquema/clientes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


    <xs:element name="usuario">
        <xs:complexType>
            <xs:sequence>


                <xs:element name="cliente">
                    <xs:complexType>
                        <xs:sequence>

                            <!-- ELEMENTO NOMBRE -->
                            <xs:element name="nombre">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <!-- LONGITUD MÁXIMA Y MÍNIMA -->
                                        <xs:minLength value="5"/>
                                        <xs:maxLength value="30"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            
                            <!-- ELEMENTO SALDO -->
                            <xs:element name="saldo" type="xs:float"/>

                            <!-- ELEMENTO COMPRAS -->
                            <xs:element name="compras">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <!-- VALIDACIÓN DE EMAIL -->
                            <xs:element name="email">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <!-- ELEMENTO TELEFONO -->
                            <xs:element name="telefono">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:length value="9"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <!-- ELEMENTO IBAN -->
                            <xs:element name="iban">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="ES[0-9]{2}[ ]*[0-9]{4}[ ]*[0-9]{4}[ ]*[0-9]{2}[ ]*[0-9]{10}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>


                        </xs:sequence>
                    </xs:complexType>
                </xs:element>


            </xs:sequence>
        </xs:complexType>
    </xs:element>


</xs:schema>

=== bintidev/LenguajeMarcas/Binta - Validación-Por-Esquema/banco.xml
<?xml version="1.0" encoding="UTF-8"?>
<usuario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="clientes.xsd">

    <cliente>
        <nombre>Binta</nombre>
        <saldo>1992.56</saldo>
        <compras>0</compras>
        <email>bd90962@gmail.com</email>
        <telefono>643467898</telefono>
        <iban>ES91 2100 1234 56 0078901234</iban>
    </cliente>
    
</usuario>
